require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HiddenJobsController do

  # This should return the minimal set of attributes required to create a valid
  # HiddenJob. As you add validations to HiddenJob, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HiddenJobsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hidden_jobs as @hidden_jobs" do
      hidden_job = HiddenJob.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hidden_jobs).should eq([hidden_job])
    end
  end

  describe "GET show" do
    it "assigns the requested hidden_job as @hidden_job" do
      hidden_job = HiddenJob.create! valid_attributes
      get :show, {:id => hidden_job.to_param}, valid_session
      assigns(:hidden_job).should eq(hidden_job)
    end
  end

  describe "GET new" do
    it "assigns a new hidden_job as @hidden_job" do
      get :new, {}, valid_session
      assigns(:hidden_job).should be_a_new(HiddenJob)
    end
  end

  describe "GET edit" do
    it "assigns the requested hidden_job as @hidden_job" do
      hidden_job = HiddenJob.create! valid_attributes
      get :edit, {:id => hidden_job.to_param}, valid_session
      assigns(:hidden_job).should eq(hidden_job)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HiddenJob" do
        expect {
          post :create, {:hidden_job => valid_attributes}, valid_session
        }.to change(HiddenJob, :count).by(1)
      end

      it "assigns a newly created hidden_job as @hidden_job" do
        post :create, {:hidden_job => valid_attributes}, valid_session
        assigns(:hidden_job).should be_a(HiddenJob)
        assigns(:hidden_job).should be_persisted
      end

      it "redirects to the created hidden_job" do
        post :create, {:hidden_job => valid_attributes}, valid_session
        response.should redirect_to(HiddenJob.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hidden_job as @hidden_job" do
        # Trigger the behavior that occurs when invalid params are submitted
        HiddenJob.any_instance.stub(:save).and_return(false)
        post :create, {:hidden_job => {}}, valid_session
        assigns(:hidden_job).should be_a_new(HiddenJob)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HiddenJob.any_instance.stub(:save).and_return(false)
        post :create, {:hidden_job => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hidden_job" do
        hidden_job = HiddenJob.create! valid_attributes
        # Assuming there are no other hidden_jobs in the database, this
        # specifies that the HiddenJob created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HiddenJob.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => hidden_job.to_param, :hidden_job => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested hidden_job as @hidden_job" do
        hidden_job = HiddenJob.create! valid_attributes
        put :update, {:id => hidden_job.to_param, :hidden_job => valid_attributes}, valid_session
        assigns(:hidden_job).should eq(hidden_job)
      end

      it "redirects to the hidden_job" do
        hidden_job = HiddenJob.create! valid_attributes
        put :update, {:id => hidden_job.to_param, :hidden_job => valid_attributes}, valid_session
        response.should redirect_to(hidden_job)
      end
    end

    describe "with invalid params" do
      it "assigns the hidden_job as @hidden_job" do
        hidden_job = HiddenJob.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HiddenJob.any_instance.stub(:save).and_return(false)
        put :update, {:id => hidden_job.to_param, :hidden_job => {}}, valid_session
        assigns(:hidden_job).should eq(hidden_job)
      end

      it "re-renders the 'edit' template" do
        hidden_job = HiddenJob.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HiddenJob.any_instance.stub(:save).and_return(false)
        put :update, {:id => hidden_job.to_param, :hidden_job => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hidden_job" do
      hidden_job = HiddenJob.create! valid_attributes
      expect {
        delete :destroy, {:id => hidden_job.to_param}, valid_session
      }.to change(HiddenJob, :count).by(-1)
    end

    it "redirects to the hidden_jobs list" do
      hidden_job = HiddenJob.create! valid_attributes
      delete :destroy, {:id => hidden_job.to_param}, valid_session
      response.should redirect_to(hidden_jobs_url)
    end
  end

end
