require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JobsTagsController do

  # This should return the minimal set of attributes required to create a valid
  # JobsTag. As you add validations to JobsTag, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JobsTagsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all jobs_tags as @jobs_tags" do
      jobs_tag = JobsTag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:jobs_tags).should eq([jobs_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested jobs_tag as @jobs_tag" do
      jobs_tag = JobsTag.create! valid_attributes
      get :show, {:id => jobs_tag.to_param}, valid_session
      assigns(:jobs_tag).should eq(jobs_tag)
    end
  end

  describe "GET new" do
    it "assigns a new jobs_tag as @jobs_tag" do
      get :new, {}, valid_session
      assigns(:jobs_tag).should be_a_new(JobsTag)
    end
  end

  describe "GET edit" do
    it "assigns the requested jobs_tag as @jobs_tag" do
      jobs_tag = JobsTag.create! valid_attributes
      get :edit, {:id => jobs_tag.to_param}, valid_session
      assigns(:jobs_tag).should eq(jobs_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JobsTag" do
        expect {
          post :create, {:jobs_tag => valid_attributes}, valid_session
        }.to change(JobsTag, :count).by(1)
      end

      it "assigns a newly created jobs_tag as @jobs_tag" do
        post :create, {:jobs_tag => valid_attributes}, valid_session
        assigns(:jobs_tag).should be_a(JobsTag)
        assigns(:jobs_tag).should be_persisted
      end

      it "redirects to the created jobs_tag" do
        post :create, {:jobs_tag => valid_attributes}, valid_session
        response.should redirect_to(JobsTag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jobs_tag as @jobs_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        JobsTag.any_instance.stub(:save).and_return(false)
        post :create, {:jobs_tag => {}}, valid_session
        assigns(:jobs_tag).should be_a_new(JobsTag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        JobsTag.any_instance.stub(:save).and_return(false)
        post :create, {:jobs_tag => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jobs_tag" do
        jobs_tag = JobsTag.create! valid_attributes
        # Assuming there are no other jobs_tags in the database, this
        # specifies that the JobsTag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        JobsTag.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => jobs_tag.to_param, :jobs_tag => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested jobs_tag as @jobs_tag" do
        jobs_tag = JobsTag.create! valid_attributes
        put :update, {:id => jobs_tag.to_param, :jobs_tag => valid_attributes}, valid_session
        assigns(:jobs_tag).should eq(jobs_tag)
      end

      it "redirects to the jobs_tag" do
        jobs_tag = JobsTag.create! valid_attributes
        put :update, {:id => jobs_tag.to_param, :jobs_tag => valid_attributes}, valid_session
        response.should redirect_to(jobs_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the jobs_tag as @jobs_tag" do
        jobs_tag = JobsTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JobsTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => jobs_tag.to_param, :jobs_tag => {}}, valid_session
        assigns(:jobs_tag).should eq(jobs_tag)
      end

      it "re-renders the 'edit' template" do
        jobs_tag = JobsTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JobsTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => jobs_tag.to_param, :jobs_tag => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jobs_tag" do
      jobs_tag = JobsTag.create! valid_attributes
      expect {
        delete :destroy, {:id => jobs_tag.to_param}, valid_session
      }.to change(JobsTag, :count).by(-1)
    end

    it "redirects to the jobs_tags list" do
      jobs_tag = JobsTag.create! valid_attributes
      delete :destroy, {:id => jobs_tag.to_param}, valid_session
      response.should redirect_to(jobs_tags_url)
    end
  end

end
