require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PressMentionsController do

  # This should return the minimal set of attributes required to create a valid
  # PressMention. As you add validations to PressMention, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PressMentionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all press_mentions as @press_mentions" do
      press_mention = PressMention.create! valid_attributes
      get :index, {}, valid_session
      assigns(:press_mentions).should eq([press_mention])
    end
  end

  describe "GET show" do
    it "assigns the requested press_mention as @press_mention" do
      press_mention = PressMention.create! valid_attributes
      get :show, {:id => press_mention.to_param}, valid_session
      assigns(:press_mention).should eq(press_mention)
    end
  end

  describe "GET new" do
    it "assigns a new press_mention as @press_mention" do
      get :new, {}, valid_session
      assigns(:press_mention).should be_a_new(PressMention)
    end
  end

  describe "GET edit" do
    it "assigns the requested press_mention as @press_mention" do
      press_mention = PressMention.create! valid_attributes
      get :edit, {:id => press_mention.to_param}, valid_session
      assigns(:press_mention).should eq(press_mention)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PressMention" do
        expect {
          post :create, {:press_mention => valid_attributes}, valid_session
        }.to change(PressMention, :count).by(1)
      end

      it "assigns a newly created press_mention as @press_mention" do
        post :create, {:press_mention => valid_attributes}, valid_session
        assigns(:press_mention).should be_a(PressMention)
        assigns(:press_mention).should be_persisted
      end

      it "redirects to the created press_mention" do
        post :create, {:press_mention => valid_attributes}, valid_session
        response.should redirect_to(PressMention.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved press_mention as @press_mention" do
        # Trigger the behavior that occurs when invalid params are submitted
        PressMention.any_instance.stub(:save).and_return(false)
        post :create, {:press_mention => {}}, valid_session
        assigns(:press_mention).should be_a_new(PressMention)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PressMention.any_instance.stub(:save).and_return(false)
        post :create, {:press_mention => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested press_mention" do
        press_mention = PressMention.create! valid_attributes
        # Assuming there are no other press_mentions in the database, this
        # specifies that the PressMention created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PressMention.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => press_mention.to_param, :press_mention => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested press_mention as @press_mention" do
        press_mention = PressMention.create! valid_attributes
        put :update, {:id => press_mention.to_param, :press_mention => valid_attributes}, valid_session
        assigns(:press_mention).should eq(press_mention)
      end

      it "redirects to the press_mention" do
        press_mention = PressMention.create! valid_attributes
        put :update, {:id => press_mention.to_param, :press_mention => valid_attributes}, valid_session
        response.should redirect_to(press_mention)
      end
    end

    describe "with invalid params" do
      it "assigns the press_mention as @press_mention" do
        press_mention = PressMention.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PressMention.any_instance.stub(:save).and_return(false)
        put :update, {:id => press_mention.to_param, :press_mention => {}}, valid_session
        assigns(:press_mention).should eq(press_mention)
      end

      it "re-renders the 'edit' template" do
        press_mention = PressMention.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PressMention.any_instance.stub(:save).and_return(false)
        put :update, {:id => press_mention.to_param, :press_mention => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested press_mention" do
      press_mention = PressMention.create! valid_attributes
      expect {
        delete :destroy, {:id => press_mention.to_param}, valid_session
      }.to change(PressMention, :count).by(-1)
    end

    it "redirects to the press_mentions list" do
      press_mention = PressMention.create! valid_attributes
      delete :destroy, {:id => press_mention.to_param}, valid_session
      response.should redirect_to(press_mentions_url)
    end
  end

end
