require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScrapedJobsController do

  # This should return the minimal set of attributes required to create a valid
  # ScrapedJob. As you add validations to ScrapedJob, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScrapedJobsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all scraped_jobs as @scraped_jobs" do
      scraped_job = ScrapedJob.create! valid_attributes
      get :index, {}, valid_session
      assigns(:scraped_jobs).should eq([scraped_job])
    end
  end

  describe "GET show" do
    it "assigns the requested scraped_job as @scraped_job" do
      scraped_job = ScrapedJob.create! valid_attributes
      get :show, {:id => scraped_job.to_param}, valid_session
      assigns(:scraped_job).should eq(scraped_job)
    end
  end

  describe "GET new" do
    it "assigns a new scraped_job as @scraped_job" do
      get :new, {}, valid_session
      assigns(:scraped_job).should be_a_new(ScrapedJob)
    end
  end

  describe "GET edit" do
    it "assigns the requested scraped_job as @scraped_job" do
      scraped_job = ScrapedJob.create! valid_attributes
      get :edit, {:id => scraped_job.to_param}, valid_session
      assigns(:scraped_job).should eq(scraped_job)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScrapedJob" do
        expect {
          post :create, {:scraped_job => valid_attributes}, valid_session
        }.to change(ScrapedJob, :count).by(1)
      end

      it "assigns a newly created scraped_job as @scraped_job" do
        post :create, {:scraped_job => valid_attributes}, valid_session
        assigns(:scraped_job).should be_a(ScrapedJob)
        assigns(:scraped_job).should be_persisted
      end

      it "redirects to the created scraped_job" do
        post :create, {:scraped_job => valid_attributes}, valid_session
        response.should redirect_to(ScrapedJob.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scraped_job as @scraped_job" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScrapedJob.any_instance.stub(:save).and_return(false)
        post :create, {:scraped_job => {}}, valid_session
        assigns(:scraped_job).should be_a_new(ScrapedJob)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScrapedJob.any_instance.stub(:save).and_return(false)
        post :create, {:scraped_job => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scraped_job" do
        scraped_job = ScrapedJob.create! valid_attributes
        # Assuming there are no other scraped_jobs in the database, this
        # specifies that the ScrapedJob created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScrapedJob.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => scraped_job.to_param, :scraped_job => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested scraped_job as @scraped_job" do
        scraped_job = ScrapedJob.create! valid_attributes
        put :update, {:id => scraped_job.to_param, :scraped_job => valid_attributes}, valid_session
        assigns(:scraped_job).should eq(scraped_job)
      end

      it "redirects to the scraped_job" do
        scraped_job = ScrapedJob.create! valid_attributes
        put :update, {:id => scraped_job.to_param, :scraped_job => valid_attributes}, valid_session
        response.should redirect_to(scraped_job)
      end
    end

    describe "with invalid params" do
      it "assigns the scraped_job as @scraped_job" do
        scraped_job = ScrapedJob.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScrapedJob.any_instance.stub(:save).and_return(false)
        put :update, {:id => scraped_job.to_param, :scraped_job => {}}, valid_session
        assigns(:scraped_job).should eq(scraped_job)
      end

      it "re-renders the 'edit' template" do
        scraped_job = ScrapedJob.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScrapedJob.any_instance.stub(:save).and_return(false)
        put :update, {:id => scraped_job.to_param, :scraped_job => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scraped_job" do
      scraped_job = ScrapedJob.create! valid_attributes
      expect {
        delete :destroy, {:id => scraped_job.to_param}, valid_session
      }.to change(ScrapedJob, :count).by(-1)
    end

    it "redirects to the scraped_jobs list" do
      scraped_job = ScrapedJob.create! valid_attributes
      delete :destroy, {:id => scraped_job.to_param}, valid_session
      response.should redirect_to(scraped_jobs_url)
    end
  end

end
